### ISSUE TITLE
[Feature] Focus handling of channels.

### ISSUE THREAD

**Issue by ocelotpotpie** [Draycia/Chat#136]
### Proposed Feature Description:
This kind of harkens back to the HeroChat days, but basically it's about picking a channel and sticking to that channel until you opt to move out of it. Most (all?) chat plugins have you do something like /ch name message each time you type, which is fine but gets a bit tiring.

### Proposed Feature Functionality:
In short, a command puts whichever channel you've selected into your current send state.

Example flow:

You start in global, someone messages you in one of your channels. You switch to that channel:
`/ch chicken`

Now you can just type as normal. You can still see global/other channels (or an option to disable that in a config). When you're done you type:

`/ch g` and go back to global.

Same thing would be for local chat if there's a radius. Or any other channel, basically.

This prevents you from having to type `/ch chicken Yeah okay` and then `/ch chicken Let's go` when you're trying to talk inside a specific channel.

**Comment by Draycia** [comment]
While this is a fundamental aspect of Carbon, I'll keep this issue open and add some notes onto it until channels are fully implemented.

Whispers and groups will have this behaviour as well.

You'll be able to select a player to message and you'll be able to directly message them as if the two of you have your own personal channel.

Groups will be pretty much the same, except they're invite/accept, you can't randomly start group DMs and force people into them. The exact implementation and behaviour of groups is yet to be determined, and discussion on that will begin at a later date.

**Comment by cades66** [comment]
I actually like this a lot, but something I personally think would be kinda cool would be the ability to have a message sent to a channel with a specific part of the message acting as a flag. Instead of having to do /ch join {channel} or full commands, what about having a wildcard character acting as that? For example, instead of writing the command to join a channel and then typing your message & having to leave after, what if it was just $ {message} to send to a specific channel? The $ would act as a wildcard, and could of course be changed. I've seen ChatControl red do this.

**Comment by Draycia** [comment]
Specifically, command usage will be as follows:

`/global` will set the Global channel as your selected channel.
Any messages you send in chat will then on be sent in the Global channel (your currently selected channel).

`/global <message>` will send a message in the global channel without setting it as your selected channel.
If you're in, say, a Staff channel and you use this command you'll remain in the staff channel.

Whispers will behave the exact same, but with a config option to disable the ability to select it as a channel.
So that admins may preserve typical whisper command behaviour (similar to how essentials does whispers).

**Comment by Draycia** [comment]
To add onto that, Carbon 1.0.0 had a feature in which you could declare symbols or characters that'll do similar to the `/ch <message>` command. You could say any message starting with a `$` or `$ ` will be auto sent to Global, for example.

I'm not opposed to carrying this feature over to carbon 2.0.0 if it'll be used.

**Comment by Draycia** [comment]
All of this is implemented apart from whisper and group DM "channels", that'll happen some point later on.
